#!/usr/bin/env node

// TODO: Fix this issue and refactor the entire file.
/* eslint-disable @typescript-eslint/no-var-requires */

// Recompile baseline ink files with specified cli compiler
//
// Usage
// node src/tests/compile.js # uses inklecate from $PATH
// node src/tests/compile.js "node dist/inkjs-compiler.js" # uses inkjs-compiler

let childProcess = require("child_process");
let glob = require("glob");
let fs = require("fs-extra");
let path = require("path");

let fileDirectory = path.join(__dirname, "inkfiles");
let inkFileDirectory = path.join(fileDirectory, "original");
let compiledFileDirectory = path.join(fileDirectory, "compiled");

// These files require the `-c` flag so that all visits will
// be counted.
let filesRequiringCFlag = [
  "visit_counts_when_choosing.ink",
  "turns_since_with_variable_target.ink",
  "read_count_variable_target.ink",
  "tests.ink",
];

// TODO: Remove these files from disk and add their content in the tests
//       directly. Since they don't compile, they won't need to be diffed
//       to ensure the generated bytecode is identical between inklecate
//       inkjs.
let filesExpectedToFailCompilation = [
  "disallow_empty_diverts.ink",
  "divert_not_found_error.ink",
  "argument_name_collisions.ink",
  "function_call_restrictions.ink",
  "function_purity_checks.ink",
  "wrong_variable_divert_target_reference.ink",
  "empty_thread_error.ink",
  "const_redefinition.ink",
  "require_variable_targets_typed.ink",
  "temp_not_allowed_cross_stitch.ink",
  "nested_choice_error.ink",
  "stitch_naming_collision.ink",
  "end_of_content_function.ink",
  "end_of_content_return_statement.ink",
  "variable_naming_collision_with_arg.ink",
  "variable_naming_collision_with_flow.ink",
  "variable_name_colision_with_flow.ink",
  "variable_name_collision_with_arg.ink",
  "weave_point_naming_collision.ink",
];

function runInklecate(input, output, inklecate, extraArgs) {
  let command = `${inklecate} ${extraArgs} -o "${output}" "${input}"`;

  return new Promise((resolve, reject) => {
    childProcess.exec(command, (error, stdout) => {
      if (error) {
        let fileName = path.basename(input);
        if (filesExpectedToFailCompilation.includes(fileName)) {
          resolve(stdout);
          return;
        }

        // Adding stdout as well, in case this is a compilation error.
        reject(new Error(`${error.message.replace(/\n+$/, "")}\n${stdout}`));
      } else {
        resolve(stdout);
      }
    });
  });
}

async function compileInkFile(inklecate) {
  console.log("Compiling test cases…");

  let files = glob.sync(`${inkFileDirectory}/**/!(includes)/*.ink`);

  let promises = files.map(async (file) => {
    let out = path.join(
      compiledFileDirectory,
      path.relative(inkFileDirectory, file) + ".json"
    );
    let fileName = path.basename(file);

    let extraArgs = "";

    if (filesRequiringCFlag.includes(fileName)) {
      extraArgs = "-c";
    }

    let outDirectory = path.dirname(out);

    await fs.ensureDir(outDirectory);
    return runInklecate(file, out, inklecate, extraArgs);
  });

  let results = await Promise.allSettled(promises);
  let errors = results.filter((result) => result.status === "rejected");

  if (errors.length === 0) {
    console.log("Done.");
  } else {
    errors.forEach((error) => console.error(`\n${error.reason.message.substring(0,255)}`));
  }
}

let inklecate = process.argv[2];

if (!inklecate || inklecate === "") {
  inklecate = "inklecate";
}

void compileInkFile(inklecate);
