LIST l = A, (B), (C), (D), E
{LIST_RANDOM(l)}
{LIST_RANDOM (l)}
{LIST_RANDOM (l)}
{LIST_RANDOM (l)}
{LIST_RANDOM (l)}
{LIST_RANDOM (l)}
{LIST_RANDOM (l)}
{LIST_RANDOM (l)}
{LIST_RANDOM (l)}
{LIST_RANDOM (l)}
